export const PLANS = {
  STARTER: {
    name: "Starter",
    priceMonthly: 49,
    priceAnnual: 39,
    maxClients: 3,
    maxPostsPerMonth: 150,
    maxSocialAccounts: 6,
    maxImagesPerMonth: 50,
    features: [
      "3 client profiles",
      "150 AI posts/month",
      "Auto publishing",
      "Basic analytics",
      "Email support",
    ],
    batchGeneration: false,
    clientPortals: false,
    whiteLabel: false,
  },
  GROWTH: {
    name: "Growth",
    priceMonthly: 149,
    priceAnnual: 119,
    maxClients: 10,
    maxPostsPerMonth: 500,
    maxSocialAccounts: 25,
    maxImagesPerMonth: 200,
    features: [
      "10 client profiles",
      "500 AI posts/month",
      "30-day batch generation",
      "Advanced analytics",
      "Client portals",
      "Priority email support",
    ],
    batchGeneration: true,
    clientPortals: true,
    whiteLabel: false,
  },
  AGENCY: {
    name: "Agency",
    priceMonthly: 299,
    priceAnnual: 239,
    maxClients: -1, // unlimited
    maxPostsPerMonth: 2000,
    maxSocialAccounts: -1,
    maxImagesPerMonth: 1000,
    features: [
      "Unlimited clients",
      "2,000 AI posts/month",
      "White label branding",
      "Full analytics suite",
      "Client portals",
      "99.5% SLA",
      "Priority support",
    ],
    batchGeneration: true,
    clientPortals: true,
    whiteLabel: true,
  },
  ENTERPRISE: {
    name: "Enterprise",
    priceMonthly: -1, // custom
    priceAnnual: -1,
    maxClients: -1,
    maxPostsPerMonth: -1,
    maxSocialAccounts: -1,
    maxImagesPerMonth: -1,
    features: [
      "Everything in Agency",
      "Custom post limits",
      "Dedicated support",
      "99.9% SLA",
      "Custom integrations",
      "SSO",
    ],
    batchGeneration: true,
    clientPortals: true,
    whiteLabel: true,
  },
} as const;

export type PlanKey = keyof typeof PLANS;
